### ISSUE TITLE
Need to implement SVG rendering from a geometry

### ISSUE THREAD

**Issue by daynin** [TerraFactory/tilegenerator#1]
To do this we can use some kind of SVG library written in golang (for example SVGO)

**Comment by iLikeKoffee** [comment]
First of all we need to implement basic math, as described in #2.

**Comment by daynin** [comment]
I think, it's not so necessary for now, we can just render a geometry into a file without exact inscribing of the geometry in tiles. What do you think?

**Comment by iLikeKoffee** [comment]
Basic geometry implemented. in `feature/svg`. Today I will implement GeometryCollection rendering and send a PR.

**Comment by daynin** [comment]
@iLikeKoffee ok
