### ISSUE TITLE
GoGEOS panics in concurrent environment

### ISSUE THREAD

**Issue by iLikeKoffee** [TerraFactory/tilegenerator#6]
Seems that Geos binding is not thread-safe. It's very bad.
At least for now, we need only WKT parsing. 
I did not find any Go implementation except [this](https://github.com/mb0/wkt). 
It's not full and seems a bit inconsistent, but it's a good place to start.

**Comment by daynin** [comment]
@iLikeKoffee 
Ok, let's use that library. It looks like pretty simple piece of code, which we can improve later (or maybe we'll develop our own library for WTK parsing)

**Comment by daynin** [comment]
We've developed our own WKT-parser (https://github.com/TerraFactory/wktparser). And we use it to avoid this issue.
