### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by iLikeKoffee** [TerraFactory/tilegenerator#9]
We definitely should organize code in our project to get a kind of `MV*` and logical structure.
For now, I see the following modules:

1. db
    - models
    - running queries
    - database management(migrations? [there is a lib](https://github.com/mattes/))
2. geo
    - tile computing(coords conversion, etc)
    - geometry/geography operations
3. rendering
    - rendering postgis geometries to svg
    - svg rasterization
4. request handling

Have i missed something?

**Comment by daynin** [comment]
@iLikeKoffee 
> 4. request handling

It will be a part of another project (tileserver).

> Have i missed something?

I think, we definitely will miss some modules/packages or something else in the start of the project, but as  a common idea of projects structuring it looks pretty good for me.
